name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        containers: [1,2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm run start
          parallel: true
          wait-on: "http://localhost:3000"
